// Code generated by sqlboy. DO NOT EDIT.
package gorm

import "time"

type ProductInfo struct {
	Id        uint32    `gorm:"column:id" json:"id"`                 //自增ID
	ProductId string    `gorm:"column:product_id" json:"product_id"` //商品编号
	SkuId     string    `gorm:"column:sku_id" json:"sku_id"`         //sku
	Status    int8      `gorm:"column:status" json:"status"`         //商品状态
	CreatedAt time.Time `gorm:"column:created_at" json:"created_at"` //创建时间
	UpdatedAt time.Time `gorm:"column:updated_at" json:"updated_at"` //修改时间
}

func (*ProductInfo) TableName() string {
	return `product_info`
}

type OrderInfo struct {
	Id        uint32    `gorm:"column:id" json:"id"`                 //自增ID
	OrderId   string    `gorm:"column:order_id" json:"order_id"`     //订单号
	Status    int8      `gorm:"column:status" json:"status"`         //订单状态
	CreatedAt time.Time `gorm:"column:created_at" json:"created_at"` //创建时间
	UpdatedAt time.Time `gorm:"column:updated_at" json:"updated_at"` //修改时间
}

func (*OrderInfo) TableName() string {
	return `order_info`
}
