// Code generated by sqlBoy. DO NOT EDIT.
package gorm

import "context"

type Transaction interface {
	InTx(context.Context, func(ctx context.Context) error) error
}

func NewTransaction(d *Dao) Transaction {
	return d
}
