// Code generated by sqlboy. DO NOT EDIT.
package sqlx

import "time"

type OrderInfo struct {
	Id        uint32    `db:"id" json:"id"`                 //自增ID
	OrderId   string    `db:"order_id" json:"order_id"`     //订单号
	Status    int8      `db:"status" json:"status"`         //订单状态
	CreatedAt time.Time `db:"created_at" json:"created_at"` //创建时间
	UpdatedAt time.Time `db:"updated_at" json:"updated_at"` //修改时间
}

func (*OrderInfo) TableName() string {
	return `order_info`
}

type ProductInfo struct {
	Id        uint32    `db:"id" json:"id"`                 //自增ID
	ProductId string    `db:"product_id" json:"product_id"` //商品编号
	SkuId     string    `db:"sku_id" json:"sku_id"`         //sku
	Status    int8      `db:"status" json:"status"`         //商品状态
	CreatedAt time.Time `db:"created_at" json:"created_at"` //创建时间
	UpdatedAt time.Time `db:"updated_at" json:"updated_at"` //修改时间
}

func (*ProductInfo) TableName() string {
	return `product_info`
}
